In [130]:
import pandas as pd
import numpy as np
from dateutil import parser, relativedelta


df = pd.read_csv('/anime.csv')
df.head(5)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [131]:
df.shape

(50, 3)

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rank    50 non-null     int64
 1   Title   50 non-null     object
 2   Score   50 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ KB

In [133]:
df.isna().sum()

Rank     0
Title    0
Score    0
dtype: int64

In [134]:
df.describe()

           Rank     Score
count  50.00000  50.00000
mean   25.50000   8.88320
std    14.57738   0.11722
min     1.00000   8.71000
25%    13.25000   8.79000
50%    25.50000   8.85500
75%    37.75000   8.99000
max    50.00000   9.10000

**New col for episode count**

In [135]:
df['Episodes'] = df['Title'].str.extract(r'\((\d+)')

In [136]:
df.head(5)

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

**Make a new col for time stamp**

In [137]:
df.loc[2,'Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [138]:
df['Time_stamp'] = df['Title'].str.extract(r'([A-Za-z]{3} \d{4} - [A-Za-z]{3} \d{4})')

In [139]:
df.head(5)

,Rank,Title,Score,Episodes,Time_stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [140]:
df.head(5)

,Rank,Title,Score,Episodes,Time_stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

**Calcuate duration from time stamp**

In [146]:
def duration_in_days(date_range: str) -> int:
    # Split the range
    start_str, end_str = date_range.split(" - ")

    # Convert to datetime (using first day of the month)
    start_date = pd.to_datetime(start_str, format="%b %Y")
    end_date = pd.to_datetime(end_str, format="%b %Y")

    # Calculate difference
    duration = (end_date - start_date).days

    return duration
#print(calculate_duration("Apr 2009 - Jul 2010"))

In [149]:
df['Duration_days'] = df['Time_stamp'].apply(duration_in_days)

In [150]:
df.head()

,Rank,Title,Score,Episodes,Time_stamp,Duration,Duration_days
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,456,456
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,153,153
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,61,61
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,335,335
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,91,91

In [160]:
df.drop(columns=['Duration'], inplace=True)

In [161]:
df.head()

,Rank,Title,Score,Episodes,Time_stamp,Duration_days
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,456
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,153
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,61
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,335
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,91

**Anime with higest score**

In [162]:
highest_score = df['Score'].max()
anime_highest_score = df[df['Score'] == highest_score]
display(anime_highest_score)

,Rank,Title,Score,Episodes,Time_stamp,Duration_days
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,456

**Top five highest scoring anime**

In [163]:
df.sort_values(by='Score', ascending=False).head(5)

,Rank,Title,Score,Episodes,Time_stamp,Duration_days
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,456
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,153
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,61
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,335
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,91

**Anime with highest episode count**

In [164]:
df['Episodes'] = df['Episodes'].astype(int)
highest_episode = df['Episodes'].max()
anime_highest_episode = df[df['Episodes'] == highest_episode]
display(anime_highest_episode)

,Rank,Title,Score,Episodes,Time_stamp,Duration_days
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,1430

**Anime with top 5 episode count**

In [165]:
df.sort_values(by='Episodes', ascending=False).head(5)

,Rank,Title,Score,Episodes,Time_stamp,Duration_days
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,1430
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,1066
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,3347
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,516
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,518

**Longest running anime**

In [166]:
longest_duration = df['Duration_days'].max()
anime_longest_duration = df[df['Duration_days'] == longest_duration]
display(anime_longest_duration)

,Rank,Title,Score,Episodes,Time_stamp,Duration_days
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,3347